"""
Citation Verification Agent
Independently verifies statutory claims, legal references, and citations against primary legislation.
Distinguishes:
1. Explicit statutory citations found in document text
2. Legal claims generated by AI
3. Retrievable legal authorities
4. Factual verification status (SUPPORTED | PARTIALLY_SUPPORTED | NOT_SUPPORTED | UNVERIFIED)
"""
import re
from typing import Dict, Any, List
from .base_agent import BaseAgent, AgentResult, AgentFindingModel
from agent_tools.legal_sources import verify_legal_claim, search_statutory_sources, STATUTORY_KNOWLEDGE_BASE


class CitationVerificationAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="Citation Verification Agent",
            description="Verifies explicit statutory citations and AI legal claims against primary statutes to prevent legal hallucinations.",
            capabilities=["citation_verification", "statutory_grounding", "hallucination_prevention"]
        )

    def execute(self, context: Dict[str, Any]) -> AgentResult:
        doc_text = context.get("text", "")
        upstream_findings = context.get("findings", [])
        
        # 1. Scan document text for explicit statutory/case citations
        citation_matches = list(set(re.findall(
            r"\b(?:Section\s+\d+[A-Z]?|Article\s+\d+|Order\s+[IVXLCDM]+)\s+(?:of\s+(?:the\s+)?)?(?:[A-Z][A-Za-z\s,]+(?:Act|Code|Rules|Constitution),?\s+\d{4})",
            doc_text,
            re.IGNORECASE
        )))

        # Also search for general Act mentions
        act_mentions = []
        for s in STATUTORY_KNOWLEDGE_BASE:
            if re.search(rf"\b{re.escape(s['act'])}\b", doc_text, re.IGNORECASE):
                act_mentions.append(s["act"])
        act_mentions = list(set(act_mentions))

        findings: List[AgentFindingModel] = []
        verified_authorities: List[Dict[str, Any]] = []
        unverified_claims: List[str] = []

        # 2. Evaluate document text citations
        if not citation_matches and not act_mentions:
            findings.append(AgentFindingModel(
                id="cit-audit-01",
                agent="Citation Verification Agent",
                dimension="Legal",
                category="Citation Verification",
                severity="INFORMATIONAL",
                risk_score=10,
                clause_type="Document Citation Audit",
                clause_text="Document contains no explicit statutory/case citations.",
                page_number=1,
                evidence="Automated pattern scan across document text for Section/Act citations.",
                claim="Document is drafted using purely contractual covenants without citing explicit statutory sections.",
                reason="Document relies on standard commercial / conveyancing terminology without citing specific statutory provisions or case law precedents.",
                recommendation="No citation hallucination risk in original contract text. Standard statutory provisions apply by operation of Indian law.",
                source_type="DOCUMENT_TEXT",
                verification_status="TEXT_SUPPORTED",
                confidence=0.98
            ))
        else:
            for cit in citation_matches:
                v_res = verify_legal_claim(cit)
                status = v_res["status"]
                auth = v_res.get("authority")
                if status in ["SUPPORTED", "PARTIALLY_SUPPORTED"] and auth:
                    verified_authorities.append(auth)
                else:
                    unverified_claims.append(cit)
                    
                findings.append(AgentFindingModel(
                    id=f"cit-doc-{len(findings)+1}",
                    agent="Citation Verification Agent",
                    dimension="Legal",
                    category="Document Citation",
                    severity="INFORMATIONAL" if status == "SUPPORTED" else "LOW",
                    risk_score=15 if status == "SUPPORTED" else 45,
                    clause_type="Document Statutory Reference",
                    clause_text=f"Cited Reference: {cit}",
                    page_number=1,
                    evidence=cit,
                    claim=f"Verification status: {status}.",
                    reason=v_res.get("note", "Statutory cross-verification completed."),
                    recommendation="Review cited statutory provision in the context of current judicial interpretations." if status == "SUPPORTED" else "Legal authority not verified against primary Gazette records.",
                    source_type="LEGAL_SOURCE" if auth else "DOCUMENT_TEXT",
                    verification_status=status,
                    confidence=v_res["confidence"],
                    sources=[auth] if auth else []
                ))

        # 3. Evaluate AI / Agent-generated legal assertions (e.g. Section 27, Section 54, DPDP Section 8)
        legal_claims_to_check = []
        for f in upstream_findings:
            if isinstance(f, dict):
                f_reason = str(f.get("reason") or "")
                f_claim_text = str(f.get("claim") or "")
            else:
                f_reason = str(getattr(f, "reason", "") or "")
                f_claim_text = str(getattr(f, "claim", "") or "")
                
            f_claim = f"{f_reason} {f_claim_text}".strip()
            if any(k in f_claim.lower() for k in ["section", "act", "void", "breach", "dpdp", "encumbrance"]):
                legal_claims_to_check.append(f_claim[:250])

        for claim in set(legal_claims_to_check[:4]):
            v_res = verify_legal_claim(claim)
            if v_res["status"] in ["SUPPORTED", "PARTIALLY_SUPPORTED"] and v_res.get("authority"):
                verified_authorities.append(v_res["authority"])
                findings.append(AgentFindingModel(
                    id=f"cit-claim-{len(findings)+1}",
                    agent="Citation Verification Agent",
                    dimension="Legal",
                    category="Legal Claim Grounding",
                    severity="INFORMATIONAL",
                    risk_score=10,
                    clause_type="AI Legal Grounding",
                    clause_text=claim[:150] + "...",
                    page_number=1,
                    evidence=f"Matched: {v_res['authority']['act']} ({v_res['authority']['section']})",
                    claim=f"Statutory grounding: {v_res['status']}.",
                    reason=v_res["note"],
                    recommendation=f"Authority level: {v_res['authority']['authority_level']}. Verified against India Code repository.",
                    source_type="LEGAL_SOURCE",
                    verification_status=v_res["status"],
                    confidence=v_res["confidence"],
                    sources=[v_res["authority"]]
                ))

        # Summary calculation
        unique_verified = {a["id"]: a for a in verified_authorities}.values()
        num_verified = len(unique_verified)
        
        if num_verified > 0:
            summary = f"Citation verification complete: {num_verified} authoritative statutory source(s) verified (e.g., {', '.join(a['section'] for a in list(unique_verified)[:2])})."
        else:
            summary = "Citation verification complete: Document contains no explicit statutory citations; no external legal authority citations were found."

        return AgentResult(
            agent_name=self.name,
            status="success",
            confidence=0.96,
            summary=summary,
            findings=findings,
            data={
                "explicit_document_citations": citation_matches,
                "verified_authorities_count": num_verified,
                "verified_authorities": list(unique_verified),
                "unverified_claims": unverified_claims
            }
        )
